### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/PSIonic-Upgrades#2]
- [ ] Manasteel CAD Assembly, t 2.25 based on psimetal, can cast mana tricks
- [ ] Terrasteel CAD Assembly, t 2.75 based on ebony, can cast mana tricks and special tricks unique to it
- [ ] Elementium CAD Assembly, t 2.5 based on ivory, can cast Alfen mana tricks and pixie tricks
